pyuic5 add_group.ui -o ..\pyUI\add_group.py
pyuic5 add_para.ui -o ..\pyUI\add_para.py
pyuic5 add_work.ui -o ..\pyUI\add_work.py
pyuic5 design.ui -o ..\pyUI\design.py
pyuic5 profile.ui -o ..\pyUI\profile_ui.py
pyuic5 registration.ui -o ..\pyUI\registration_ui.py
pyuic5 students_for_group.ui -o ..\pyUI\students_for_group.py
pyuic5 submit_work.ui -o ..\pyUI\submit_work_ui.py
pyuic5 see_rating.ui -o ..\pyUI\see_rating.py
pyuic5 set_rating.ui -o ..\pyUI\set_rating.py
pyuic5 works_for_lesson.ui -o ..\pyUI\works_for_lesson.py
pyuic5 works_for_lesson.ui -o ..\pyUI\works_for_lesson.py